global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'fraud-detector'
    static_configs:
      - targets: ['fraud-detector:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

