# Logging Configuration
version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s - %(lineno)d - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/fraud_detection.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
  
  json:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/fraud_detection.json
    maxBytes: 10485760  # 10MB
    backupCount: 5

loggers:
  fraud_detection:
    level: DEBUG
    handlers: [console, file, json]
    propagate: false
  
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: false
  
  fastapi:
    level: INFO
    handlers: [console]
    propagate: false

root:
  level: INFO
  handlers: [console]

